name: Reuse Me
on:
  workflow_call:
    inputs:
      regionsJSON:
        description: "Regions as an array [au, jp, uk]"
        required: true
        type: string

jobs:
  setup:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.setVariables.outputs.matrix }}
    steps:
      - id: setVariables
        run: |
          echo "matrix=$input" >> $GITHUB_OUTPUT
          echo "# matrix=$input" >> $GITHUB_STEP_SUMMARY
        env:
          input: ${{ inputs.regionsJSON }}
          
  run_tests:
    runs-on: ubuntu-latest
    needs: setup
    strategy:
      fail-fast: false
#      matrix:
#        region: ${{fromJSON(needs.setup.outputs.matrix)}}
    steps:
      - name: Running tests
        run: |
          echo "${{needs.setup.outputs.matrix}}"
#          echo "I am running tests for region: ${{ matrix.region }}
