name: Reuse Me
on:
  workflow_call:
    inputs:
      regionsJSON:
        description: "Regions as an array [au, jp, uk]"
        required: true
        type: string

jobs:
  setup:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.setVariables.outputs.matrix }}
    steps:
      - id: setVariables
        run: |
          echo "matrix=${{ inputs.regionsJSON }}" >> $GITHUB_OUTPUT
          echo "# Running tests on regions: ${{ inputs.regionsJSON }}" >> $GITHUB_STEP_SUMMARY
  
  run_tests:
    runs-on: ubuntu-latest
    needs: setup
    strategy:
      fail-fast: false
      matrix:
        region: ${{fromJSON(needs.setup.outputs.matrix)}}
    steps:
      - name: Running tests
        run: |
          echo "I am running tests for region: ${{ matrix.region }}"
#          echo "${{needs.setup.outputs.matrix}}"
